DROP TABLE games;
CREATE TABLE games (
  gid INTEGER PRIMARY KEY,
  cid INTEGER NOT NULL,
  bid INTEGER,
  wid INTEGER,
  ended INTEGER NOT NULL DEFAULT(0),
  size INTEGER NOT NULL DEFAULT(19)
);

DROP TABLE moves;
CREATE TABLE moves (
  mid INTEGER PRIMARY KEY,
  gid INTEGER NOT NULL,
  color CHAR NOT NULL, 
  mv TEXT NOT NULL, 
  eaten INTEGER NOT NULL DEFAULT(0),
  FOREIGN KEY(gid) REFERENCES games(gid)
);
